# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grp_regex = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_regex.setObjectName("grp_regex")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.grp_regex)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_regex = QtWidgets.QLineEdit(self.grp_regex)
        self.le_regex.setObjectName("le_regex")
        self.horizontalLayout.addWidget(self.le_regex)
        self.pb_generate_fa = QtWidgets.QPushButton(self.grp_regex)
        self.pb_generate_fa.setObjectName("pb_generate_fa")
        self.horizontalLayout.addWidget(self.pb_generate_fa)
        self.verticalLayout_2.addWidget(self.grp_regex)
        self.grp_graph = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_graph.setObjectName("grp_graph")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_graph)
        self.gridLayout.setObjectName("gridLayout")
        self.tabwdg_graph = QtWidgets.QTabWidget(self.grp_graph)
        self.tabwdg_graph.setObjectName("tabwdg_graph")
        self.tab_nfa = QtWidgets.QWidget()
        self.tab_nfa.setObjectName("tab_nfa")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_nfa)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphview_nfa = GraphView(self.tab_nfa)
        self.graphview_nfa.setObjectName("graphview_nfa")
        self.gridLayout_2.addWidget(self.graphview_nfa, 0, 0, 1, 1)
        self.tabwdg_graph.addTab(self.tab_nfa, "")
        self.tab_dfa = QtWidgets.QWidget()
        self.tab_dfa.setObjectName("tab_dfa")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_dfa)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphview_dfa = GraphView(self.tab_dfa)
        self.graphview_dfa.setObjectName("graphview_dfa")
        self.gridLayout_3.addWidget(self.graphview_dfa, 0, 0, 1, 1)
        self.tabwdg_graph.addTab(self.tab_dfa, "")
        self.tab_min_nfa = QtWidgets.QWidget()
        self.tab_min_nfa.setObjectName("tab_min_nfa")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_min_nfa)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphview_min_dfa = GraphView(self.tab_min_nfa)
        self.graphview_min_dfa.setObjectName("graphview_min_dfa")
        self.gridLayout_4.addWidget(self.graphview_min_dfa, 0, 0, 1, 1)
        self.tabwdg_graph.addTab(self.tab_min_nfa, "")
        self.gridLayout.addWidget(self.tabwdg_graph, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grp_graph)
        self.grp_test = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_test.setEnabled(False)
        self.grp_test.setObjectName("grp_test")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.grp_test)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.te_test_str = QtWidgets.QTextEdit(self.grp_test)
        self.te_test_str.setObjectName("te_test_str")
        self.horizontalLayout_2.addWidget(self.te_test_str)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_test_match = QtWidgets.QPushButton(self.grp_test)
        self.pb_test_match.setObjectName("pb_test_match")
        self.verticalLayout.addWidget(self.pb_test_match)
        self.pb_test_search = QtWidgets.QPushButton(self.grp_test)
        self.pb_test_search.setObjectName("pb_test_search")
        self.verticalLayout.addWidget(self.pb_test_search)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.grp_test)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabwdg_graph.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.le_regex, self.pb_generate_fa)
        MainWindow.setTabOrder(self.pb_generate_fa, self.tabwdg_graph)
        MainWindow.setTabOrder(self.tabwdg_graph, self.graphview_nfa)
        MainWindow.setTabOrder(self.graphview_nfa, self.te_test_str)
        MainWindow.setTabOrder(self.te_test_str, self.pb_test_match)
        MainWindow.setTabOrder(self.pb_test_match, self.pb_test_search)
        MainWindow.setTabOrder(self.pb_test_search, self.graphview_dfa)
        MainWindow.setTabOrder(self.graphview_dfa, self.graphview_min_dfa)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "正规表达式与自动机"))
        self.grp_regex.setTitle(_translate("MainWindow", "正规表达式"))
        self.pb_generate_fa.setText(_translate("MainWindow", "生成自动机"))
        self.pb_generate_fa.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.grp_graph.setTitle(_translate("MainWindow", "自动机图示"))
        self.tabwdg_graph.setTabText(self.tabwdg_graph.indexOf(self.tab_nfa), _translate("MainWindow", "NFA"))
        self.tabwdg_graph.setTabText(self.tabwdg_graph.indexOf(self.tab_dfa), _translate("MainWindow", "DFA"))
        self.tabwdg_graph.setTabText(self.tabwdg_graph.indexOf(self.tab_min_nfa), _translate("MainWindow", "最小化DFA"))
        self.grp_test.setTitle(_translate("MainWindow", "字符串测试"))
        self.pb_test_match.setText(_translate("MainWindow", "匹配"))
        self.pb_test_match.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.pb_test_search.setText(_translate("MainWindow", "查找"))
        self.pb_test_search.setShortcut(_translate("MainWindow", "F3"))
from ui.GraphView import GraphView
